EBAY_PARAMS = 'XXX;YYY;ZZZ;000'
SMS_NUMBER = '5551234567'
REPORT_PATH = '~/webapps/static/ebay/report.html'
REPORT_URL = 'http://static.website.com/ebay/report.html'
TIME_ZONE = 'US/Central'
AWS_PARAMS = 'XXX;YYY'
